package errlist

import "errors"

var (
	ERR_NOT_REACH              = errors.New("[DLP] code should not reach here")
	ERR_HAS_NOT_CONFIGED       = errors.New("[DLP] Engine has not been configed yet, call ApplyConfig* API")
	ERR_CONF_EMPTY             = errors.New("[DLP] configString is empty")
	ERR_CONFURL_EMPTY          = errors.New("[DLP] configURL is empty")
	ERR_CONFPATH_EMPTY         = errors.New("[DLP] confPath is empty")
	ERR_CONF_VERIFY_FAILED     = errors.New("[DLP] config verify failed")
	ERR_DISABLE_RULE_FAILED    = errors.New("[DLP] rule is in DisableRules but not found in Rules")
	ERR_AUTH_FAILED            = errors.New("[DLP] Authentication Failed")
	ERR_REMOTE_CFG_FAILED      = errors.New("[DLP] remote config failed, will load default config")
	ERR_PROCESS_AFTER_CLOSE    = errors.New("[DLP] Engine has been closed")
	ERR_NEWENGINE_DEBUG        = errors.New("[DLP] NewEngineDebug is only used for debug, register your psm on DLP management system.")
	ERR_MAX_INPUT_LIMIT        = errors.New("[DLP] exceed max input limitation")
	ERR_POSITION_ERROR         = errors.New("[DLP] length of posistion parameter must be 2")
	ERR_REGEX_NEED_STRING      = errors.New("[DLP] Regex value should be string")
	ERR_REGEX_COMPILE_FAILED   = errors.New("[DLP] Regex compile error")
	ERR_DICT_NEED_STRING_ARRAY = errors.New("[DLP] Dict rule needs string array")
	ERR_RE_EMPTY               = errors.New("[DLP] re object is nil")
	ERR_MASKWORKER_NOTFOUND    = errors.New("[DLP] mask worker not found")
	ERR_LOADMASK_NAME_CONFLICT = errors.New("[DLP] Load mask rule name conflict")
	ERR_PANIC                  = errors.New("[DLP] Panic in DLP")
	ERR_MASK_NOT_SUPPORT       = errors.New("[DLP] Mask Method not support")
	ERR_MASK_FAILED            = errors.New("[DLP] Mask Failed, input is returned")
	ERR_MASK_TAG_NOT_SUPPORT   = errors.New("[DLP] Mask() dose not support with MaskType: Tag, which is used in Deiendity()")
	ERR_MASKName_CONFLICT      = errors.New("[DLP] MaskName conflicts with MaskRules.RuleName")
	ERR_MASK_RULE_NOTFOUND     = errors.New("[DLP] Mask Rule is not Found")
	ERR_DATA_MARSHAL           = errors.New("[DLP] data marshal error")
	ERR_SEND_REQUEST           = errors.New("[DLP] sendRequest error")
	ERR_MASK_STRUCT_INPUT      = errors.New("[DLP] input of MaskStruct must be a pointer of a strcut")
	ERR_MASK_STRUCT_OUTPUT     = errors.New("[DLP] Internal Error of MaskStruct, output is nil")
	ERR_ONLY_FOR_LOG           = errors.New("[DLP] NewLogProcessor() has been called. engine can be only used for log")
)
